// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJiXeNWVGVVcBknFWZOAKlTjvCR5SwUUo',
    appId: '1:470702482795:web:0f858d7b7144d97137582e',
    messagingSenderId: '470702482795',
    projectId: 'authenticate-33840',
    authDomain: 'authenticate-33840.firebaseapp.com',
    storageBucket: 'authenticate-33840.appspot.com',
    measurementId: 'G-TV7QRWYRDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH5IkOhtwoYckLzbPeW41sXCj5yJeWMFw',
    appId: '1:470702482795:android:4884ec3fdd94701937582e',
    messagingSenderId: '470702482795',
    projectId: 'authenticate-33840',
    storageBucket: 'authenticate-33840.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzgsQPWH37wx4L8YBC76roU69XuBXslWE',
    appId: '1:470702482795:ios:9316fa106092579b37582e',
    messagingSenderId: '470702482795',
    projectId: 'authenticate-33840',
    storageBucket: 'authenticate-33840.appspot.com',
    iosClientId: '470702482795-93ln3qae05t0ssqdso7prlejol62cm7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthExp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzgsQPWH37wx4L8YBC76roU69XuBXslWE',
    appId: '1:470702482795:ios:9316fa106092579b37582e',
    messagingSenderId: '470702482795',
    projectId: 'authenticate-33840',
    storageBucket: 'authenticate-33840.appspot.com',
    iosClientId: '470702482795-93ln3qae05t0ssqdso7prlejol62cm7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthExp',
  );
}
